# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  variable:  # id of input
    description: "variable"
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.variable }}